version: "3.8"

services:

    clickhouse_server:
        image: clickhouse/clickhouse-server:22.8.15.23-alpine
        restart: unless-stopped
        volumes:
            -   clickhouse_data_vol:/var/lib/clickhouse
        environment:
            -   CLICKHOUSE_USER=default
            -   CLICKHOUSE_PASSWORD=hello2Jaeger
            -   CLICKHOUSE_DB=jaeger
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s

    jaeger_collector:
        image: jaegertracing/jaeger-collector:1.43
        restart: unless-stopped
        environment:
            -   SPAN_STORAGE_TYPE=grpc-plugin
        command:
            -   "--grpc-storage-plugin.binary=/etc/jaeger-clickhouse/jaeger-clickhouse-plugin"
            -   "--grpc-storage-plugin.configuration-file=/etc/jaeger-clickhouse/config.yml"
        volumes:
            -   ./jaeger-clickhouse-binary:/etc/jaeger-clickhouse
        ports:
            -   "14250:14250"
        depends_on:
            clickhouse_server:
                    condition: service_healthy

    jaeger_query:
        image: jaegertracing/jaeger-query:1.43
        restart: unless-stopped
        environment:
            -   SPAN_STORAGE_TYPE=grpc-plugin
        command:
            - "--grpc-storage-plugin.binary=/etc/jaeger-clickhouse/jaeger-clickhouse-plugin"
            - "--grpc-storage-plugin.configuration-file=/etc/jaeger-clickhouse/config.yml"
        volumes:
            - ./jaeger-clickhouse-binary:/etc/jaeger-clickhouse
        ports:
            -   "16686:16686"
        depends_on:
            clickhouse_server:
                    condition: service_healthy

    oauth2_proxy:
        build:
            context: ./oauth2-proxy
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
            -   ./oauth2-proxy/proxy.env
        volumes:
            -   /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt

volumes:
    clickhouse_data_vol: